# CI Configuration for Azure Pipelines

pool:
  vmImage: "Ubuntu 16.04"

variables:
  GOBIN: "$(GOPATH)/bin"
  GOROOT: "/usr/local/go1.12"
  GOPATH: "$(system.defaultWorkingDirectory)/go_code"
  GO111MODULE: "on"

steps:
  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      shopt -s extglob
      shopt -s dotglob
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: "Set up the Go workspace"

  - script: |
      go mod verify
      go get github.com/jstemmer/go-junit-report
      go get github.com/axw/gocov/gocov
      go get github.com/AlekSi/gocov-xml
    displayName: "Get dependencies"

  - script: |
      go test ./... -v -coverprofile=coverage.txt -covermode count 2>&1 | go-junit-report > junit.xml
      gocov convert coverage.txt > coverage.json
      gocov-xml < coverage.json > coverage.xml
      mkdir reports
      cp junit.xml ./reports/junit.xml
      cp coverage.xml ./reports/coverage.xml
    displayName: "Run unit tests"

  - task: PublishTestResults@2
    displayName: "Publish test results"
    inputs:
      testRunner: JUnit
      testResultsFiles: "./reports/junit.xml"

  - task: PublishCodeCoverageResults@1
    displayName: "Publish test coverage"
    inputs:
      codeCoverageTool: "cobertura"
      summaryFileLocation: "./reports/coverage.xml"
      reportDirectory: "./reports/"